export interface NLPResult {
  intent: string;
  engine?: 'regex' | 'ollama';
  language?: 'es' | 'en' | 'mixed';
  sanitized?: boolean;
  entities: {
    animeTitle?: string;
    query?: string;
    refIndexOrTitle?: string;
    source?: 'local' | 'online';
    genre?: string;
    year?: number;
    season?: string;
    studio?: string;
    format?: 'tv' | 'movie' | 'ova' | 'ona' | 'special' | 'music' | 'donghua';
    formats?: Array<'tv' | 'movie' | 'ova' | 'ona' | 'special' | 'music' | 'donghua'>;
    durationPreference?: 'short' | 'medium' | 'long';
    duration_max?: number;
    min_episodes?: number;
    max_episodes?: number;
    tags?: string[];
    exclude_tags?: string[];
    toneTags?: string[];
    dislikedToneTags?: string[];
    status?: string;
    airing_status?: 'finished' | 'airing' | 'upcoming';
    score?: number;
    min_score?: number;
    max_score?: number;
    year_from?: number;
    year_to?: number;
    exclude_titles?: string[];
    title_1?: string;
    title_2?: string;
    franchise?: string;
    seasons?: number[];
    episodeNumber?: number;
    field?: 'episodes' | 'start_date' | 'synopsis' | 'score' | 'studio' | 'next_episode_date' | 'next_season_date';
    sort_by?: 'score_asc' | 'score_desc' | 'release_date_asc' | 'release_date_desc' | 'popularity_desc';
    staff?: string;
    staff_role?: 'director' | 'voice_actor' | 'original_creator';
    source_material?: string;
    demographic?: string;
    exclude_franchise?: string;
    exclude_related_to?: string;
    exclude_origin?: string;
    semantic_hint?: string | boolean;
    context_continuation?: boolean;
    page?: number;
    exclude_last_shown?: boolean;
    session_only?: boolean;
    temporal_bypass?: boolean;
    preference?: 'positive' | 'negative';
    action?: 'reset_weight';
    limit?: number;
    list?: string;
    role?: string;
    concept?: string;
  };
}
